# Generated by Django 2.1.7 on 2019-03-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impression',
            name='image',
            field=models.ImageField(blank=True, upload_to='pictures'),
        ),
    ]
