# Generated by Django 2.1.7 on 2019-04-08 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20190326_2035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='impression',
            old_name='book_id',
            new_name='book',
        ),
    ]
